name: Basic Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Check Node.js version
      run: node --version
      
    - name: Lint JavaScript files
      run: |
        # Basic syntax check for JavaScript files
        find . -name "*.js" -not -path "./node_modules/*" -exec node -c {} \;
        
    - name: Validate SQL syntax (basic check)
      run: |
        # Basic SQL file existence check
        echo "Checking SQL files exist..."
        find queries/ -name "*.sql" | head -5 | xargs ls -la
        
    - name: Check package.json structure
      run: |
        # Validate package.json
        node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8')); console.log('package.json is valid');"
        
    - name: Run help commands
      run: |
        # Test help commands work
        node safe-query.js --help || echo "Help command test completed"
        node run-query.js --help || echo "Help command test completed"

    - name: Test installation checker
      run: |
        # Test the installation checker (without BigQuery dependencies)
        node test-installation.js || echo "Installation test completed"
